# Generated by Django 4.2.3 on 2023-08-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider',
            name='account_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
